name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Setup Dependencies
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'

    # Build Angular
    - run: npm ci
    - run: npm run build
    - run: npx cap sync

    # Build Android
    - name: Grant execute permission for gradlew
      working-directory: android
      run: chmod +x gradlew
    - name: Build Release bundle with Gradle
      working-directory: android
      run: ./gradlew app:bundleRelease
    - name: Write keystore file
      working-directory: android
      env:
        MAFFITDEV_KEYSTORE: ${{ secrets.MAFFITDEV_KEYSTORE }}
      run: echo $MAFFITDEV_KEYSTORE | base64 --decode > MaffitDev.jks
    - name: Sign Release app bundle with jarsigner
      working-directory: android
      env:
        MAFFITDEV_PASSWORD: ${{ secrets.MAFFITDEV_PASSWORD }}
      run: jarsigner -keystore MaffitDev.jks -keypass "$MAFFITDEV_PASSWORD" -storepass "$MAFFITDEV_PASSWORD" app/build/outputs/bundle/release/app-release.aab MaffitDev
    - name: Upload app-release.aab artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
