# This is a basic workflow that is manually triggered

name: Manual workflow
run-name: Deploy ${{ inputs.tag }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: environment

jobs:
  deploy-cloud:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying cloud
      run: echo "Deploying tag ${{ inputs.tag }} to cloud ${{ inputs.environment }}"

  deploy-mobile:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying mobile
      run: echo "Deploying tag ${{ inputs.tag }} to mobile ${{ inputs.environment }}"

